apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patchesStrategicMerge:
  - patches/server-service-clusterip.yaml
  - patches/argocd-server-ingress.yaml
  - patches/git-7solutions-secret.yaml
  - patches/argocd-rbac-cm.yaml